PerformansYonetimSistemi/Models/Defination/Position.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PerformansYonetimSistemi.Models.Defination
{
    public class Position:Base
    {
        [Key]
        [Required]
        [DisplayName("Kod")]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [DisplayName("Aktif")]
        public bool IsActive { get; set; } = true;
        [Required]
        public string DepartmentCode { get; set; } 

    }
}

PerformansYonetimSistemi/Controllers/Defination/PositionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PerformansYonetimSistemi.Helper.Database;
using PerformansYonetimSistemi.Models.Defination;
using PerformansYonetimSistemi.ViewModels;

namespace PerformansYonetimSistemi.Controllers.Defination
{
    public class PositionController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PositionController(ApplicationDbContext context)
        {
            _context = context;
        }
        MainViewModel mvm;
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            ViewBag.CurrentPage = "/Position/List";
            mvm = new MainViewModel
            {
                Positions = await _context.Positions.Where(w => w.IsActive).OrderBy(o => o.DepartmentCode).ThenBy(t=>t.Name).ToListAsync(),
                Departments = await _context.Departments.Where(w => w.IsActive).OrderBy(t => t.Name).ToListAsync()
            };
            return View(mvm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(Position position)
        {
            if (_context.Positions.Where(w => w.Code == position.Code).Any())
            {
                ViewBag.errorTitle = "Hata";
                ViewBag.error = position.Code + " kodu ile daha önce kayıt yapılmıştır. Başka kod kullanarak kayıt yapınız.";
                return View("Error");
            }
            _context.Add(position);
            _context.SaveChanges();
            return RedirectToAction("List");
        }
        [Authorize]
        [HttpPost]
        public IActionResult Delete(string Code)
        {
            Position position = _context.Positions.FirstOrDefault(w => w.Code == Code);
            _context.Remove(position);
            _context.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

PerformansYonetimSistemi/Views/Position/List.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["Title"] = "Pozisyon";
}
<div class="col-sm-8">
    <form asp-controller="Position" asp-action="Create" method="post" class="card mb-1">
        <div class="card-body">
            <div class="col-sm-12 d-flex justify-content-between">
                <div class="col-sm-9 d-flex">
                    <div class="col-sm-4 me-1">
                        <select class="form-select form-select-sm fs--2" name="DepartmentCode">
                            @foreach (var item in Model.Departments)
                            {
                                <option value="@item.Code">@item.Name</option>
                            }
                        </select>
                    </div>
                    <div class="col-sm-2 me-1">
                        <input class="form-control form-control-sm fs--2 text-center" type="text" placeholder="Kod" name="Code">
                    </div>
                    <div class="col-sm-6">
                        <input class="form-control form-control-sm fs--2 text-center" type="text" placeholder="Açıklama" name="Name">
                    </div>
                </div>
                <div class="col-sm-2">
                    <button class="btn btn-sm btn-outline-success w-100 h-100" type="submit">
                        <span class="fa fa-plus"></span> EKLE
                    </button>
                </div>
            </div>
        </div>
    </form>
    <div class="card">
        <div class="card-body">
            <table class="table table-sm table-bordered table-striped fs--2">
                <thead>
                    <tr>
                        <th class="text-center">Departman</th>
                        <th class="text-center">Kod</th>
                        <th class="text-center">Açıklama</th>
                        <th class="text-center">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Positions)
                    {
                        <tr>
                            <td class="text-center align-middle">@Model.Departments.Where(w=>w.Code==item.DepartmentCode).Select(s=>s.Name).FirstOrDefault()</td>
                            <td class="text-center align-middle">@item.Code</td>
                            <td class="text-center align-middle">@item.Name</td>
                            <td class="text-center align-middle">
                                <form asp-controller="Position" asp-action="Delete" method="post">
                                    <button class="btn btn-sm btn-outline-danger fs--2" value="@item.Code" name="Code">
                                        <span class="far fa-trash-alt"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>