PerformansYonetimSistemi/Models/Defination/Evaluation.cs
using System.ComponentModel.DataAnnotations;

namespace PerformansYonetimSistemi.Models.Defination
{
    public class Evaluation:Base
    {
        [Key]
        public int Id { get; set; }
        public required string Code { get; set; }
        public required string Explanation { get; set; }
    }
}

PerformansYonetimSistemi/Models/Defination/EvaluationForm.cs
using System.ComponentModel.DataAnnotations;

namespace PerformansYonetimSistemi.Models.Defination
{
    public class EvaluationForm : Base
    {
        [Key]
        public int Id { get; set; }
        public string EvaluationCode { get; set; }
        public int FormId { get; set; }
    }
}

PerformansYonetimSistemi/Models/HR/NeedToFillForm.cs
using System.ComponentModel.DataAnnotations;

namespace PerformansYonetimSistemi.Models.HR
{
    public class NeedToFillForm:Base
    {
        [Key]
        public int Id { get; set; }
        public int MasId { get; set; }
        public int DetailId { get; set; }
        public string Guid { get; set; }
        public string? Explanation { get; set; }
        public int TextLevel { get; set; }
        public string? Title { get; set; }
        public string? LowerTitle { get; set; }
        public int Sequence { get; set; }
        public string? GivenPoint { get; set; }
        public string Employee { get; set; }
        public int? Manager { get; set; }
        public DateTime? FormDate { get; set; }
    }
}

PerformansYonetimSistemi/Controllers/Defination/EvaluationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PerformansYonetimSistemi.Helper;
using PerformansYonetimSistemi.Helper.Database;
using PerformansYonetimSistemi.Models.Defination;
using PerformansYonetimSistemi.Models.HR;
using PerformansYonetimSistemi.ViewModels;
using System.Net.Mail;
using System.Text;

namespace PerformansYonetimSistemi.Controllers.Defination
{
    public class EvaluationController : Controller
    {
        private readonly ApplicationDbContext _context;
        public EvaluationController(ApplicationDbContext context)
        {
            _context = context;
        }
        MainViewModel mvm;
        #region Evaluation
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.CurrentPage = "/Evaluation/Create";
            mvm = new MainViewModel
            {
                Evaluations = _context.Evaluations.ToList()
            };
            return View(mvm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(Evaluation evaluation)
        {
            if (_context.Evaluations.Where(w => w.Code == evaluation.Code).Any())
            {
                ViewBag.errorTitle = "Hata";
                ViewBag.error = evaluation.Code + " kodu ile daha önce kayıt yapılmıştır. Başka kod kullanarak kayıt yapınız.";
                return View("Error");
            }
            _context.Add(evaluation);
            _context.SaveChanges();
            return RedirectToAction("Create");
        }
        [Authorize]
        [HttpPost]
        public IActionResult Delete(string Code)
        {
            Evaluation evaluation = _context.Evaluations.FirstOrDefault(w => w.Code == Code);
            _context.Remove(evaluation);
            _context.SaveChanges();
            return RedirectToAction("Create");
        }
        #endregion
        #region Send Forms
        [Authorize]
        public async Task<IActionResult> CheckForms(string Code)
        {
            ViewBag.CurrentPage = "/Evaluation/Create";
            mvm = new MainViewModel
            {
                FormMases = await _context.FormMas.ToListAsync(),
                Evaluations = await _context.Evaluations.Where(w => w.Code == Code).ToListAsync(),
            };

            return View(mvm);
        }
        [Authorize]
        public async Task<IActionResult> ShowForm(int id, string Code)
        {
            ViewBag.CurrentPage = "/Evaluation/Create";
            mvm = new MainViewModel
            {
                FormMases = await _context.FormMas.Where(w => w.Id == id).ToListAsync(),
                FormDetails = await _context.FormDetails.Where(w => w.MasId == id).ToListAsync(),
                Evaluations = await _context.Evaluations.Where(w => w.Code == Code).ToListAsync()
            };
            return View(mvm);
        }
        [Authorize]
        public async Task<IActionResult> SendSelection(int id, string Code)
        {
            ViewBag.CurrentPage = "/Evaluation/Create";
            mvm = new MainViewModel
            {
                FormMases = await _context.FormMas.Where(w => w.Id == id).ToListAsync(),
                Employees = await _context.Employees.ToListAsync(),
                Evaluations = await _context.Evaluations.Where(w => w.Code == Code).ToListAsync()
            };
            return View(mvm);
        }
        [Authorize]
        public void createEvaluationForm(int id, string Code)
        {
            EvaluationForm evaluationForm = new EvaluationForm();
            evaluationForm.FormId = id;
            evaluationForm.EvaluationCode = Code;
            _context.Add(evaluationForm);
            _context.SaveChanges();
        }
        [Authorize]
        public void sendMail(int id, string employees, string btnAction, string Code)
        {
            createEvaluationForm(id, Code);
            string html = "";
            List<Tuple<string, string, string>> employeeList = new List<Tuple<string, string, string>>();

            string[] employeeData = employees.Split(',');

            foreach (string data in employeeData)
            {
                string[] parts = data.Split(';');
                if (parts.Length == 3)
                {
                    string sicilNo = parts[0];
                    string employeeMail = parts[1];
                    string managerMail = parts[2];
                    employeeList.Add(new Tuple<string, string, string>(sicilNo, employeeMail, managerMail));
                }
            }
            mvm = new MainViewModel
            {
                FormDetails = _context.FormDetails.Where(w => w.MasId == id).ToList(),
            };

            NeedToFillForm needToFillForm;
            foreach (var employee in employeeList)
            {
                html = "https://pys.ekmasconnect.com:797/Evaluation/NeedToFillForm?guid=";
                string guid = Guid.NewGuid().ToString();
                foreach (var item in mvm.FormDetails.Where(w => w.TextLevel == 0).OrderBy(o => o.Sequence))
                {
                    needToFillForm = new NeedToFillForm();
                    needToFillForm.Guid = guid;
                    needToFillForm.MasId = id;
                    needToFillForm.DetailId = item.Id;
                    needToFillForm.Explanation = item.Explanation;
                    needToFillForm.TextLevel = item.TextLevel;
                    needToFillForm.Title = item.Title;
                    needToFillForm.LowerTitle = item.LowerTitle;
                    needToFillForm.Sequence = item.Sequence;
                    needToFillForm.GivenPoint = "0";
                    needToFillForm.Employee = employee.Item1;
                    if (btnAction == "manager")
                    {
                        needToFillForm.Manager = 1;
                    }
                    else
                    {
                        needToFillForm.Manager = 0;
                    }
                    needToFillForm.FormDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                    needToFillForm.CreatedAt = DateTime.Now;
                    needToFillForm.CreatedBy = User.Identity.Name == null ? "mert.baggbasi" : User.Identity.Name;

                    _context.Add(needToFillForm);
                    _context.SaveChanges();
                    foreach (var itemLt in mvm.FormDetails.Where(w => w.TextLevel == 1 && w.Title == item.Id.ToString() && !string.IsNullOrEmpty(w.Title)).OrderBy(o => o.Sequence))
                    {
                        needToFillForm = new NeedToFillForm();
                        needToFillForm.Guid = guid;
                        needToFillForm.MasId = id;
                        needToFillForm.DetailId = itemLt.Id;
                        needToFillForm.Explanation = itemLt.Explanation;
                        needToFillForm.TextLevel = itemLt.TextLevel;
                        needToFillForm.Title = itemLt.Title;
                        needToFillForm.LowerTitle = itemLt.LowerTitle;
                        needToFillForm.Sequence = itemLt.Sequence;
                        needToFillForm.GivenPoint = "0";
                        needToFillForm.Employee = employee.Item1;
                        if (btnAction == "manager")
                        {
                            needToFillForm.Manager = 1;
                        }
                        else
                        {
                            needToFillForm.Manager = 0;
                        }
                        needToFillForm.FormDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                        needToFillForm.CreatedAt = DateTime.Now;
                        needToFillForm.CreatedBy = User.Identity.Name == null ? "mert.baggbasi" : User.Identity.Name;

                        _context.Add(needToFillForm);
                        _context.SaveChanges();
                        foreach (var itemDt in mvm.FormDetails.Where(w => w.TextLevel == 2 && w.LowerTitle == itemLt.Id.ToString() && !string.IsNullOrEmpty(w.LowerTitle)).OrderBy(o => o.Sequence))
                        {
                            needToFillForm = new NeedToFillForm();
                            needToFillForm.Guid = guid;
                            needToFillForm.MasId = id;
                            needToFillForm.DetailId = itemDt.Id;
                            needToFillForm.Explanation = itemDt.Explanation;
                            needToFillForm.TextLevel = itemDt.TextLevel;
                            needToFillForm.Title = itemDt.Title;
                            needToFillForm.LowerTitle = itemDt.LowerTitle;
                            needToFillForm.Sequence = itemDt.Sequence;
                            needToFillForm.GivenPoint = "0";
                            needToFillForm.Employee = employee.Item1;
                            if (btnAction == "manager")
                            {
                                needToFillForm.Manager = 1;
                            }
                            else
                            {
                                needToFillForm.Manager = 0;
                            }
                            needToFillForm.FormDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                            needToFillForm.CreatedAt = DateTime.Now;
                            needToFillForm.CreatedBy = User.Identity.Name == null ? "mert.baggbasi" : User.Identity.Name;

                            _context.Add(needToFillForm);
                            _context.SaveChanges();
                        }
                    }
                }
                string adiSoyadi = _context.Employees.Where(w => w.IsActive && w.TC == employee.Item1).Select(s => s.Name + " " + s.LastName).FirstOrDefault();

PerformansYonetimSistemi/Views/Evaluation/AlreadyCompleted.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PerformansYonetimSistemi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PerformansYonetimSistemi.styles.css" asp-append-version="true" />
</head>

<body>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="card">
                <div class="card-body text-center">
                    <h1>From daha önce doldurulmuştur..!</h1>
                    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-patch-exclamation text-warning" viewBox="0 0 16 16">
                        <path d="M7.001 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.553.553 0 0 1-1.1 0z" />
                        <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911z" />
                    </svg>
                </div>
            </div>
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - PerformansYonetimSistemi - İnsan Kaynakları Müdürlüğü
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

PerformansYonetimSistemi/Views/Evaluation/CheckForms.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewBag.Title = "Form Listesi";
}
<div class="card">
    <div class="card-body">
        <div class="col-sm-12">
            <table class="table table-sm table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Kod</th>
                        <th>İsim</th>
                        <th>Açıklama</th>
                        <th class="text-center">Oluşturan</th>
                        <th class="text-center">Oluşturma Tarihi</th>
                        <th class="text-end">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.FormMases.OrderBy(o => o.Id))
                    {
                        <tr>
                            <td class="text-center">@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Explanation</td>
                            <td class="text-center">@item.CreatedBy</td>
                            <td class="text-center">@item.CreatedAt.ToString("dd.MM.yyyy HH:ss")</td>
                            <td class="d-flex justify-content-end">
                                <form asp-controller="Evaluation" asp-action="ShowForm">
                                    <button class="btn btn-sm btn-outline-primary me-2" name="Id" value="@item.Id">
                                        <span class="fas fa-expand-alt"></span>
                                    </button>
                                    <input class="d-none" name="Code" value="@Model.Evaluations.Select(s=>s.Code).FirstOrDefault()" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

PerformansYonetimSistemi/Views/Evaluation/Create.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["title"] ="Değerlendirme";
}
<div class="card mb-1">
    <div class="card-header">
        <h4>Değerlendirme</h4>
    </div>
    <div class="card-body">
        <form asp-controller="Evaluation" asp-action="Create" class="col-sm-12 d-flex justify-content-between">
            <div class="col-sm-2">
                <input class="form-control" type="text" name="Code" placeholder="Kod" required />
            </div>
            <div class="col-sm-7">
                <input class="form-control" type="text" name="Explanation" placeholder="Açıklama" required />
            </div>
            <div class="col-sm-2">
                <button class="btn btn-outline-success w-100 h-100">Ekle</button>
            </div>
        </form>
    </div>
</div>
<div class="card mb-1">
    <div class="card-body">
        <table class="table table-sm fs--2 table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th class="text-center">Kod</th>
                    <th class="text-center">Açıklama</th>
                    <th class="text-center">İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Evaluations)
                {
                    <tr>
                        <td class="text-center align-middle">@item.Code</td>
                        <td class="align-middle">@item.Explanation</td>
                        <td class="text-center align-middle d-flex justify-content-center">
                            <form asp-controller="Evaluation" asp-action="Delete" method="post">
                                <button class="btn btn-sm btn-outline-danger fs--2 me-1" value="@item.Code" name="Code">
                                    <span class="far fa-trash-alt"></span>
                                </button>
                            </form>
                            <form asp-controller="Evaluation" asp-action="CheckForms" method="get">
                                <button class="btn btn-sm btn-outline-primary fs--2" value="@item.Code" name="Code">
                                    <span class="fas fa-arrow-right"></span>
                                </button>
                            </form>
                            
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

PerformansYonetimSistemi/Views/Evaluation/FormCompleted.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PerformansYonetimSistemi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PerformansYonetimSistemi.styles.css" asp-append-version="true" />
</head>

<body>
<div class="container">
    <main role="main" class="pb-3">
        <div class="card">
            <div class="card-body text-center">
                <h1>From Başarıyla Gönderilmiştir</h1>
                <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-check-circle text-success" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"></path>
                    <path d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"></path>
                </svg>
            </div>
        </div>
    </main>
</div>
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - PerformansYonetimSistemi - İnsan Kaynakları Müdürlüğü
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

PerformansYonetimSistemi/Views/Evaluation/SendSelection.cshtml
@using PerformansYonetimSistemi.Helper;
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["Title"] = "Gönderim Seçim Listesi";
    Functions functions = new Functions();
}
<h2>Çalışan Listesi</h2>
<div class="card col-sm-12 bg-secondary">
    <div class="card-body">
        <div class="col-sm-12 d-flex justify-content-between">
            <div>
                <button class="btn btn-primary" type="button" onclick="selectAll()">Tüm Çalışanları Seç</button>
            </div>
            <div class="d-flex">
                <form asp-controller="Evaluation" asp-action="sendMail">
                    <button class="btn btn-outline-warning me-1" type="submit" onmouseover="getManagers();getEmployees()" name="btnAction" value="manager">Amirlere Mail At</button>
                    <input class="d-none" id="employeesInputm" name="employees" />
                    <input class="d-none" type="number" name="id" value="@Model.FormMases.Select(s=>s.Id).FirstOrDefault()" />
                    <input class="d-none" name="Code" value="@Model.Evaluations.Select(s=>s.Code).FirstOrDefault()" />
                </form>
                <form asp-controller="Evaluation" asp-action="sendMail">
                    <button class="btn btn-outline-info" type="submit" onmouseover="getEmployees()" name="btnAction" value="employee">Çalışanlara Mail At</button>
                    <input class="d-none" id="employeesInput" name="employees" />
                    <input class="d-none" type="number" name="id" value="@Model.FormMases.Select(s=>s.Id).FirstOrDefault()" />
                    <input class="d-none" name="Code" value="@Model.Evaluations.Select(s=>s.Code).FirstOrDefault()" />
                </form>
            </div>
        </div>
    </div>
</div>
<div class="card col-sm-12">
    <div class="card-body">
        <table class="table table-sm table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th class="text-center">T.C Kimlik No</th>
                    <th>Adı Soyadı</th>
                    <th class="text-center">Görev/Ünvan</th>
                    <th class="text-center">Departman</th>
                    <th class="text-center">İşe Giriş Tarihi</th>
                    <th class="text-center">Kıdem Süresi</th>
                    <th class="text-center">Mail</th>
                    <th class="text-center">Toplam İş Tecrübesi (Yıl)</th>
                    <th class="text-center">Yöneticisi</th>
                    <th class="text-center">Müdürü</th>
                    <th class="text-center">Genel Müdür</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Employees.OrderBy(o => o.Name).ThenBy(t => t.LastName))
                {
                    // Tarihler arasındaki farkı bul
                    TimeSpan fark = DateTime.Now - @item.DateOfRecruitment;

                    // Yılları ve ayları hesapla
                    int yilFarki = (int)(fark.TotalDays / 365.25); // ortalama yıl uzunluğu kullanarak
                    int ayFarki = (int)((fark.TotalDays % 365.25) / 30.436875); // ortalama ay uzunluğu kullanarak
                    string kidemSuresi = "";
                    // Sonucu yazdır
                    if (yilFarki > 0)
                    {
                        kidemSuresi = $"{yilFarki} yıl {ayFarki} ay";
                    }
                    else
                    {
                        kidemSuresi = $"{ayFarki} ay";
                    }
                    <tr>
                        <td class="white-space-nowrap text-center align-middle">
                            <input class="form-check-input text-center" type="checkbox" name="cbox" />
                        </td>
                        <td class="text-center text-nowrap">@item.TC</td>
                        <td class="text-center text-nowrap">@item.Name @item.LastName</td>
                        <td class="text-center text-nowrap">@item.Position</td>
                        <td class="text-center text-nowrap">@item.Department</td>
                        <td class="text-center text-nowrap">@item.DateOfRecruitment.ToString("dd.MM.yyyy")</td>
                        <td class="text-center text-nowrap">@kidemSuresi</td>
                        <td class="text-center text-nowrap">@item.Mail</td>
                        <td class="text-center text-nowrap">@(item.TotalWorkExperience == 0 ? "" : item.TotalWorkExperience)</td>
                        <td class="text-center text-nowrap">@item.Responsible</td>
                        <td class="text-center text-nowrap">@item.IsManager</td>
                        <td class="text-center text-nowrap">@item.IsGM</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    function selectAll() {
        var cbox = document.getElementsByName('cbox');
        for (i = 0; i < cbox.length; i++) {
            if (cbox[i].checked) {
                cbox[i].checked = false;
            } else {
                cbox[i].checked = true;
            }
        }
    };
    function getEmployees() {
        var cbox = document.getElementsByName('cbox');
        var selectedEmployees = "";
        for (i = 0; i < cbox.length; i++) {
            if (cbox[i].checked) {
                selectedEmployees = selectedEmployees + cbox[i].parentNode.parentNode.children[1].innerHTML + ";" + cbox[i].parentNode.parentNode.children[10].innerHTML + ";" + cbox[i].parentNode.parentNode.children[9].innerHTML + ",";
            }
        }
        selectedEmployees = selectedEmployees.substring(0, selectedEmployees.length - 1);
        document.getElementById('employeesInput').value = selectedEmployees;
        document.getElementById('employeesInputm').value = selectedEmployees;
    };
</script>