PerformansYonetimSistemi/Models/Defination/KPI.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace PerformansYonetimSistemi.Models.Defination
{
    public class KPI:Base
    {
        [Key]
        [Required]
        [DisplayName("Kod")]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Departmant { get; set; }

        [Required]
        [DisplayName("Aktif")]
        public bool IsActive { get; set; } = true;
    }
}

PerformansYonetimSistemi/Controllers/Defination/KPIController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PerformansYonetimSistemi.Helper.Database;
using PerformansYonetimSistemi.Models.Defination;
using PerformansYonetimSistemi.ViewModels;

namespace PerformansYonetimSistemi.Controllers.Defination
{
    public class KPIController : Controller
    {
        private readonly ApplicationDbContext _context;
        public KPIController(ApplicationDbContext context)
        {
            _context = context;
        }
        MainViewModel mvm;
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DepartmanFilter()
        {
            ViewBag.CurrentPage = "/KPI/DepartmanFilter";
            mvm = new MainViewModel
            {
                Departments = await _context.Departments.Where(w => w.IsActive).OrderBy(t => t.Name).ToListAsync()
            };
            return View(mvm);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> List(string Code)
        {
            ViewBag.CurrentPage = "/KPI/DepartmanFilter";
            mvm = new MainViewModel
            {
                KPIs = await _context.KPIs.Where(w => w.IsActive && w.Departmant == Code).OrderBy(t => t.Name).ToListAsync()
            };
            ViewBag.Departmant = Code;
            return View(mvm);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(KPI kpi)
        {
            if (_context.KPIs.Where(w => w.Code == kpi.Code).Any())
            {
                ViewBag.errorTitle = "Hata";
                ViewBag.error = kpi.Code + " kodu ile daha önce kayıt yapılmıştır. Başka kod kullanarak kayıt yapınız.";
                return View("Error");
            }
            _context.Add(kpi);
            _context.SaveChanges();
            return RedirectToAction("List", new { Code = kpi.Departmant });
        }
        [Authorize]
        [HttpPost]
        public IActionResult Delete(string Code)
        {
            KPI kpi = _context.KPIs.FirstOrDefault(w => w.Code == Code);
            string departmant = kpi.Departmant;
            _context.Remove(kpi);
            _context.SaveChanges();
            return RedirectToAction("List", new { Code = departmant });
        }
        [Authorize]
        public async Task<IActionResult> Card()
        {
            ViewBag.CurrentPage = "/KPI/Card";
            mvm = new MainViewModel
            {
                KPIs = await _context.KPIs.Where(w => w.IsActive).ToListAsync(),
                Targets = await _context.Targets.Where(w => w.IsActive).ToListAsync()
            };
            mvm.Employees = await _context.Employees.Where(w => w.IsActive && mvm.Targets.Select(s => s.Employee).Contains(w.TC)).ToListAsync();
            return View(mvm);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CardToEmployee(string TC, string route, DateTime startDate, DateTime endDate)
        {
            int kpiId = 0;
            if (route == "new")
            {
                if (_context.EmployeeKpis.Where(w => w.TC == TC && w.StartDate <= startDate && w.EndDate >= startDate).Any())
                {
                    ViewBag.errorTitle = "Hata";
                    ViewBag.error = "Başlangıç tarihi, mevcut Performans Kartı dönem aralığında olamaz..!";
                    return View("Error");
                }
                else
                {
                    EmployeeKpi employeeKpi = new EmployeeKpi();
                    employeeKpi.TC = TC;
                    employeeKpi.StartDate = startDate;
                    employeeKpi.EndDate = endDate;
                    employeeKpi.CreatedBy = "mert.bagbasi";
                    _context.Add(employeeKpi);
                    _context.SaveChanges();

                    kpiId = _context.EmployeeKpis.Where(w => w.TC == TC).OrderByDescending(o => o.Id).Select(s => s.Id).FirstOrDefault();

                    return RedirectToAction("EmployeeCard", new { TC = TC, kpiId = kpiId });
                }
            }
            else if (route == "edit")
            {
                return RedirectToAction("EmployeeCardEdit", new { TC = TC });
            }
            return RedirectToAction("EmployeeCard");
        }
        [Authorize]
        public async Task<IActionResult> EmployeeCardEdit(string TC)
        {
            ViewBag.CurrentPage = "/KPI/Card";
            mvm = new MainViewModel
            {
                Positions = await _context.Positions.Where(w => w.IsActive).ToListAsync(),
                Departments = await _context.Departments.Where(w => w.IsActive).ToListAsync(),
                Employees = await _context.Employees.Where(w => w.TC == TC).ToListAsync()
            };
            mvm.Targets = await _context.Targets.Where(w => w.IsActive && w.Employee == TC).ToListAsync();
            mvm.KPIs = await _context.KPIs.Where(w => w.IsActive && mvm.Targets.Select(s => s.KpiCode).Contains(w.Code)).ToListAsync();
            mvm.EmployeeKpis = await _context.EmployeeKpis.Where(w => w.TC == TC && (w.StartDate >= DateTime.Now || w.EndDate>=DateTime.Now)).ToListAsync();
            mvm.PerformanceCards = await _context.PerformanceCards.Where(w => mvm.TargetPeriods.Select(s => s.Id).Contains(w.TargetPeriodId)).ToListAsync();
            if (!mvm.EmployeeKpis.Where(w=> mvm.PerformanceCards.Select(s=>s.TargetPeriodId).Contains(w.Id)).Any())
            {
                List<EmployeeKpi> employeeKpis = _context.EmployeeKpis.Where(w => w.TC == TC && !mvm.PerformanceCards.Select(s => s.TargetPeriodId).Contains(w.Id)).ToList();
                _context.RemoveRange(employeeKpis);
                _context.SaveChanges();
            }
            return View(mvm);
        }
        [Authorize]
        public async Task<IActionResult> EmployeeCard(string TC, int kpiId)
        {
            ViewBag.CurrentPage = "/KPI/Card";
            mvm = new MainViewModel
            {
                Positions = await _context.Positions.Where(w => w.IsActive).ToListAsync(),
                Departments = await _context.Departments.Where(w => w.IsActive).ToListAsync(),
                Employees = await _context.Employees.Where(w => w.TC == TC).ToListAsync(),
                PerformanceCards = await _context.PerformanceCards.Where(w => w.TargetPeriodId == kpiId).ToListAsync()
            };
            mvm.Targets = await _context.Targets.Where(w => w.IsActive && w.Employee == TC).ToListAsync();
            mvm.KPIs = await _context.KPIs.Where(w => w.IsActive && mvm.Targets.Select(s => s.KpiCode).Contains(w.Code)).ToListAsync();
            mvm.EmployeeKpis = await _context.EmployeeKpis.Where(w => w.Id == kpiId).ToListAsync();
            return View(mvm);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EmployeeCard(PerformanceCard PerformanceCard)
        {
            PerformanceCard.CreatedBy = "mert.bagbasi";
            if (!_context.PerformanceCards.Where(w => w.TargetPeriodId == PerformanceCard.TargetPeriodId && w.TargetId==PerformanceCard.TargetId).Any())
            {
                _context.Add(PerformanceCard);
                _context.SaveChanges();
            }
            string TC = _context.EmployeeKpis.FirstOrDefault(f => f.Id == PerformanceCard.TargetPeriodId).TC;
            return RedirectToAction("EmployeeCard", new { TC = TC, kpiId = PerformanceCard.TargetPeriodId });
        }
        [Authorize]
        public async Task<IActionResult> DeletePerformanceCard(int Id)
        {
            PerformanceCard PerformanceCard = _context.PerformanceCards.Where(w => w.Id == Id).FirstOrDefault();
            int kpiId = PerformanceCard.TargetPeriodId;
            _context.Remove(PerformanceCard);
            _context.SaveChanges();
            string TC = await _context.EmployeeKpis.Where(w => w.Id == kpiId).Select(s => s.TC).FirstOrDefaultAsync();
            return RedirectToAction("EmployeeCard", new { TC = TC, KpiId = kpiId });
        }

        #region Performance Card Filter
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> PerformanceCardFilter()
        {
            ViewBag.CurrentPage = "/KPI/PerformanceCardFilter";
            mvm = new MainViewModel
            {
                KPIs = await _context.KPIs.Where(w => w.IsActive).ToListAsync(),
                Employees = await _context.Employees.Where(w => w.IsActive).OrderBy(t => t.Name).ToListAsync(),
            };
            mvm.Departments = await _context.Departments.Where(w => w.IsActive && mvm.KPIs.Select(s => s.Departmant).Contains(w.Code)).OrderBy(t => t.Name).ToListAsync();
            return View(mvm);
        }
        #endregion
        #region Select Period
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Period(string DepartmanCode, string TC)
        {
            ViewBag.CurrentPage = "/KPI/PerformanceCardFilter";
            mvm = new MainViewModel
            {
                TargetPeriods = await _context.TargetPeriods.Where(w => w.IsActive && w.Department == DepartmanCode && w.Employee == TC).ToListAsync()
            };
            mvm.Targets= await _context.Targets.Where(w=>mvm.TargetPeriods.Select(s=>s.Id).Contains(w.TargetPeriodId)).ToListAsync();
            ViewBag.Department = DepartmanCode;
            ViewBag.Employee = TC;
            return View(mvm);
        }
        #endregion
        #region Adjust Calculation of the KPI Score Card
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ScoreCard(int Id)
        {
            ViewBag.CurrentPage = "/KPI/PerformanceCardFilter";
            mvm = new MainViewModel
            {
                TargetPeriods =await _context.TargetPeriods.Where(s => s.Id == Id).ToListAsync(),
               
            };

PerformansYonetimSistemi/Views/KPI/Card.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["title"] = "Performans Kart Oluştur";
}
<style>
    .choices {
        font-size: 0.6944444444rem !important;
    }

    .choices__inner {
        font-size: 0.6944444444rem !important;
        min-height: 24.66px !important;
        padding: 0px 0px 0px 0px;
        line-height: 0rem !important;
    }

    .choices__list--multiple .choices__item {
        font-size: 0.6944444444rem !important;
    }

    .choices__list--dropdown .choices__item {
        font-size: 0.6944444444rem !important;
    }

    .choices__list--dropdown .choices__item--selectable::after {
        font-size: 8px !important;
    }

    .choices__heading {
        font-size: 8px !important;
    }

    .choices__input {
        font-size: 12px !important;
    }
</style>
<form asp-controller="KPI" asp-action="CardToEmployee" method="post" class="col-sm-12 d-flex justify-content-between">
    <div class="card col-sm-4">
        <div class="card-body">
            <select class="form-select form-select-sm fs--2 js-choice" name="TC" data-options='{"removeItemButton":true,"placeholder":true,"searchResultLimit":10}' required>
                <option class="fs--2" value="">Çalışan Seçiniz...</option>
                @foreach (var item in Model.Employees)
                {
                    <option class="fs--2" value="@item.TC">@item.Name @item.LastName</option>
                }
            </select>
        </div>
    </div>
    <div class="card col-sm-8 ms-1">
        <div class="card-body">
            <div class="col-sm-12 d-flex justify-content-between">
                <button class="btn btn-outline-success" style="width:48%" type="button" data-bs-toggle="modal" data-bs-target="#dateModal">Yeni Oluştur</button>
                <button class="btn btn-outline-primary" style="width:48%" type="submit" name="route" value="edit">Mevcut Kartı Düzenle</button>
            </div>
        </div>
    </div>
    <div class="modal fade" id="dateModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 500px">
            <div class="modal-content position-relative">
                <div class="modal-body p-0">
                    <div class="rounded-top-lg py-3 ps-4 pe-6 bg-light">
                        <h4 class="mb-1" id="modalExampleDemoLabel">Kart Dönem Aralığı Tarih Girişi</h4>
                    </div>
                    <div class="p-4 pb-0">
                        <div class="mb-3">
                            <label class="col-form-label" for="recipient-name">Başlangıç Tarihi</label>
                            <input class="form-control" type="date" name="startDate" />
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="recipient-name">Bitiş Tarihi</label>
                            <input class="form-control" type="date" name="endDate" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" type="submit" name="route" value="new">Oluştur</button>
                </div>
            </div>
        </div>
    </div>
</form>

PerformansYonetimSistemi/Views/KPI/DepartmanFilter.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["title"] = "Departman Seçimi - KPI";
}
<form asp-controller="KPI" asp-action="List" method="get" class="card">
    <div class="card-body">
        <div class="col-sm-12 d-flex justify-content-between">
            <div class="col-sm-8">
                <select class="form-select js-choice w-100" name="Code" data-options='{"removeItemButton":true,"placeholder":true}'>
                    <option value="">Departman Seçiniz..</option>
                @foreach (var item in Model.Departments)
                    {
                        <option value="@item.Code">@item.Name</option>
                    }
                </select>
            </div>
            <div class="col-sm-2">
                <button class="btn btn-sm btn-outline-primary w-100 h-100" type="submit">
                    İlerle <span class="fas fa-forward"></span>
                </button>
            </div>
        </div>
    </div>
</form>

PerformansYonetimSistemi/Views/KPI/EmployeeCard.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["title"] = "Performans Kartı Oluştur";
}
<style>
    .choices {
        font-size: 0.6944444444rem !important;
    }

    .choices__inner {
        font-size: 0.6944444444rem !important;
        min-height: 24.66px !important;
        padding: 0px 0px 0px 0px;
        line-height: 0rem !important;
    }

    .choices__list--multiple .choices__item {
        font-size: 0.6944444444rem !important;
    }

    .choices__list--dropdown .choices__item {
        font-size: 0.6944444444rem !important;
    }

    .choices__list--dropdown .choices__item--selectable::after {
        font-size: 8px !important;
    }

    .choices__heading {
        font-size: 8px !important;
    }

    .choices__input {
        font-size: 12px !important;
    }
</style>
<div class="col-sm-12 d-flex justify-content-between">
    @foreach (var item in Model.Employees)
    {
        <div class="card col-sm-4">
            <div class="card-body fs--2">
                <div class="d-flex justify-content-between">
                    <img class="rounded-circle img-thumbnail shadow-sm" src="/img/employee/@(item.TC).jpg" width="200">
                    <div>
                        <div class="text-end">
                            <span class="badge badge-soft-warning">Performans Kartı</span>
                        </div>
                        <div class="text-end">
                            <span class="badge badge-soft-info">@Model.EmployeeKpis.Select(s=>s.StartDate.ToShortDateString()).FirstOrDefault()</span>
                            <span class="badge badge-soft-info">@Model.EmployeeKpis.Select(s=>s.EndDate.ToShortDateString()).FirstOrDefault()</span>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 mt-3">
                    <h5 class="mb-1">@item.Name @item.LastName</h5>
                    <h6 class="fs-9 fw-normal">@Model.Positions.Where(w => w.Code == item.Position).Select(s => s.Name).FirstOrDefault()</h6>
                    <p class="text-500">@Model.Departments.Where(w => w.Code == item.Department).Select(s => s.Name).FirstOrDefault()</p>
                </div>
            </div>
        </div>
    }
    <div class="card col-sm-8 ms-1 scrollbar" style="height:37vh">
        <table class="table table-sm table-hovered table-bordered table-striped fs--2">
            <thead class="position-sticky top-0 bg-secondary text-white">
                <tr>
                    <th class="text-center">KPI</th>
                    <th class="text-center">Hedef</th>
                    <th class="text-center"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Targets.Where(w => !Model.PerformanceCards.Select(s => s.TargetId).Contains(w.Id)))
                {
                    <tr>
                        <td class="align-middle text-nowrap">@Model.KPIs.Where(w=>w.Code==item.KpiCode).Select(s=>s.Name).FirstOrDefault()</td>
                        <td class="align-middle text-wrap">@item.Explanation</td>
                        <td class="text-center align-middle">
                            <form asp-controller="KPI" asp-action="EmployeeCard" method="post">
                                <button class="btn btn-sm btn-outline-success fs--2" value="@item.Id" name="TargetId">
                                    <span class="fas fa-plus"></span>
                                </button>
                                <input class="d-none" name="KpiId" type="number" value="@Model.EmployeeKpis.Select(s=>s.Id).FirstOrDefault()" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="card col-sm-12 mt-1">
    <div class="card-body">
        <div class="col-sm-12 mt-1">
            <table class="table table-sm table-striped table-bordered fs--2">
                <thead>
                    <tr class="bg-soft-primary">
                        <th class="text-center">KPI</th>
                        <th class="text-center">Hedef</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.PerformanceCards)
                    {
                        <tr>
                            <td class="align-middle text-nowrap">@Model.KPIs.Where(w=>w.Code==Model.Targets.Where(w=>w.Id==item.TargetId).Select(s=>s.KpiCode).FirstOrDefault()).Select(s=>s.Name).FirstOrDefault()</td>
                            <td class="align-middle text-wrap">@Model.Targets.Where(w => w.Id == item.TargetId).Select(s => s.Explanation).FirstOrDefault()</td>
                            <td class="text-center align-middle">
                                <form asp-controller="KPI" asp-action="DeletePerformanceCard" method="post">
                                    <button class="btn btn-sm btn-outline-danger fs--2" value="@item.Id" name="Id">
                                        <span class="far fa-trash-alt"></span>
                                    </button>
                                    <input class="d-none" name="Id" value="@item.Id" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

PerformansYonetimSistemi/Views/KPI/EmployeeCardEdit.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["title"] = "Performans Kartı Oluştur";
}
<div class="card col-sm-12">
    <div class="card-body">
        @foreach (var item in Model.Employees)
        {
            <div class="col-sm-3">
                <img class="rounded-circle img-thumbnail shadow-sm" src="/img/employee/@(item.TC).jpg" width="200">
                <div class="col-sm-12">
                    <h4 class="mb-1">@item.Name @item.LastName</h4>
                    <h5 class="fs-9 fw-normal">@Model.Positions.Where(w => w.Code == item.Position).Select(s => s.Name).FirstOrDefault()</h5>
                    <p class="text-500">@Model.Departments.Where(w => w.Code == item.Department).Select(s => s.Name).FirstOrDefault()</p>
                </div>
            </div>
        }
    </div>
</div>
@foreach (var item in Model.EmployeeKpis)
{
    int sira = 1;
    <div class="card col-sm-12 mt-1">
        <div class="card-body">
            <form asp-controller="KPI" asp-action="EmployeeCard" method="get" class="col-sm-12">
                <button class="btn btn-lg btn-outline-primary" value="@item.Id" name="kpiId">#@sira</button>
                <input class="d-none" name="TC" value="@item.TC" />
            </form>
            <div class="col-sm-12 mt-1">
                <table class="table table-sm table-striped table-bordered">
                    <thead>
                        <tr class="bg-soft-primary">
                            <th class="text-center">KPI</th>
                            <th class="text-center">Hedef</th>
                    </thead>
                    <tbody>
                        @foreach (var ksc in Model.PerformanceCards.Where(w => w.TargetPeriodId == item.Id))
                        {
                            <tr>
                                <td class="align-middle text-nowrap">@Model.KPIs.Where(w => w.Code == Model.Targets.Where(w => w.Id == ksc.TargetId).Select(s => s.KpiCode).FirstOrDefault()).Select(s => s.Name).FirstOrDefault()</td>
                                <td class="align-middle text-wrap">@Model.Targets.Where(w => w.Id == ksc.TargetId).Select(s => s.Explanation).FirstOrDefault()</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    sira++;
}

PerformansYonetimSistemi/Views/KPI/List.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["Title"] = "KPI";
}
<div class="col-sm-6">
    <form asp-controller="KPI" asp-action="Create" method="post" class="card mb-1">
        <div class="card-body">
            <div class="col-sm-12 d-flex justify-content-between">
                <div class="col-sm-6 d-flex">
                    <div class="col-sm-4 me-1">
                        <input class="form-control form-control-sm fs--2 text-center" type="text" placeholder="Kod" name="Code">
                    </div>
                    <div class="col-sm-8">
                        <input class="form-control form-control-sm fs--2 text-center" type="text" placeholder="Açıklama" name="Name">
                    </div>
                </div>
                <div class="col-sm-2">
                    <button class="btn btn-sm btn-outline-success w-100 h-100" type="submit">
                        <span class="fa fa-plus"></span> EKLE
                    </button>
                    <input class="d-none" type="text" name="Departmant" value="@ViewBag.Departmant" />
                </div>
            </div>
        </div>
    </form>
    <div class="card">
        <div class="card-body">
            <table class="table table-sm table-bordered table-striped fs--2">
                <thead>
                    <tr>
                        <th class="text-center">Kod</th>
                        <th class="text-center">Açıklama</th>
                        <th class="text-center">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.KPIs)
                    {
                        <tr>
                            <td class="text-center align-middle">@item.Code</td>
                            <td class="text-center align-middle">@item.Name</td>
                            <td class="text-center align-middle">
                                <form asp-controller="KPI" asp-action="Delete" method="post">
                                    <button class="btn btn-sm btn-outline-danger fs--2" value="@item.Code" name="Code">
                                        <span class="far fa-trash-alt"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

PerformansYonetimSistemi/Views/KPI/PerformanceCardFilter.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["title"] = "Filtre - KPI Kartı";
}
<form asp-controller="KPI" asp-action="Period" method="get" class="card">
    <div class="card-body">
        <div class="col-sm-12 mb-3">
            <select class="form-select" name="DepartmanCode" onchange="filterEmployee(this.value)">
                <option value="">Departman Seçiniz..</option>
                @foreach (var item in Model.Departments.OrderBy(o => o.Name))
                {
                    <option value="@item.Code">@item.Name</option>
                }
            </select>
        </div>
        <div class="col-sm-12 mb-3">
            <select class="form-select" name="TC">
                <option value="">Çalışan Seçiniz..</option>
                @foreach (var item in Model.Employees.OrderBy(o => o.Name).ThenBy(t => t.LastName))
                {
                    <option value="@item.TC" name="employeeFilter" department="@item.Department">@item.Name @item.LastName</option>
                }
            </select>
        </div>
        <div class="col-sm-12">
            <button class="btn btn-sm btn-outline-primary w-100 h-100" type="submit">
                İlerle <span class="fas fa-forward"></span>
            </button>
        </div>
    </div>
</form>
<script>
    function filterEmployee(departmentValue) {
        var employee = document.getElementsByName('employeeFilter');

        for (i = 0; i < employee.length; i++) {
            if (employee[i].getAttribute('department') == departmentValue) {
                employee[i].classList.remove('d-none');
            } else {
                employee[i].classList.add('d-none');
            }
        }
    }
</script>

PerformansYonetimSistemi/Views/KPI/Period.cshtml
@model PerformansYonetimSistemi.ViewModels.MainViewModel
@{
    ViewData["title"] = "Performans Kart Seçimi";
}
<div class="card mb-1">
    <div class="card-header">
        <h4 class="text-primary">KPI Kartları</h4>
    </div>
    <div class="card-body">
        <div class="col-sm-12 d-flex">
            <table class="table table-sm table-bordered">
                <thead class="bg-soft-warning">
                    <tr>
                        <th class="text-center">Başlama Tarihi</th>
                        <th class="text-center">Bitiş Tarihi</th>
                        <th class="text-center">Oluşturan</th>
                        <th class="text-center">Oluşturma Tarihi</th>
                        <th class="text-center">İşlem</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.TargetPeriods.OrderBy(o => o.StartDate))
                    {
                        <tr>
                            <td class="text-center align-middle">@item.StartDate.ToString("dd.MM.yyyy")</td>
                            <td class="text-center align-middle">@item.EndDate.ToString("dd.MM.yyyy")</td>
                            <td class="text-center align-middle">@item.CreatedBy</td>
                            <td class="text-center align-middle">@item.CreatedAt.ToString("dd.MM.yyyy HH:mm")</td>
                            <td class="text-center align-middle">
                                <form asp-controller="KPI" asp-action="ScoreCard" method="get">
                                    <button class="btn btn-sm btn-outline-primary me-2" name="Id" value="@item.Id">
                                        <span class="fas fa-expand-alt"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @foreach (var target in Model.Targets.Where(w => w.TargetPeriodId == item.Id))
                        {
                            <tr class="bg-soft-info">
                                <td class="align-middle" colspan="5">@target.Explanation</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>